/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseFooter: typeof import('./src/components/BaseFooter/BaseFooter.vue')['default']
    BaseHeader: typeof import('./src/components/BaseHeader/BaseHeader.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb/Breadcrumb.vue')['default']
    Captcha: typeof import('./src/components/Captcha/Captcha.vue')['default']
    ClassificationList: typeof import('./src/components/ClassificationList/ClassificationList.vue')['default']
    FloatButton: typeof import('./src/components/FloatButton/FloatButton.vue')['default']
    Result: typeof import('./src/components/Result/Result.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonView: typeof import('./src/components/SkeletonView/SkeletonView.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/SvgIcon.vue')['default']
    TBackTop: typeof import('tdesign-vue-next')['BackTop']
    TBreadcrumb: typeof import('tdesign-vue-next')['Breadcrumb']
    TBreadcrumbItem: typeof import('tdesign-vue-next')['BreadcrumbItem']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TDropdownItem: typeof import('tdesign-vue-next')['DropdownItem']
    TDropdownMenu: typeof import('tdesign-vue-next')['DropdownMenu']
    TFooter: typeof import('tdesign-vue-next')['Footer']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    THeader: typeof import('tdesign-vue-next')['Header']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TImage: typeof import('tdesign-vue-next')['Image']
    TImageViewer: typeof import('tdesign-vue-next')['ImageViewer']
    TInput: typeof import('tdesign-vue-next')['Input']
    TInputAdornment: typeof import('tdesign-vue-next')['InputAdornment']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TPagination: typeof import('tdesign-vue-next')['Pagination']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TStickyItem: typeof import('tdesign-vue-next')['StickyItem']
    TStickyTool: typeof import('tdesign-vue-next')['StickyTool']
    TSubmenu: typeof import('tdesign-vue-next')['Submenu']
    TSwiper: typeof import('tdesign-vue-next')['Swiper']
    TSwiperItem: typeof import('tdesign-vue-next')['SwiperItem']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    TUpload: typeof import('tdesign-vue-next')['Upload']
  }
}
